### ISSUE TITLE
When i use it and throw a exception "The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths."

### ISSUE THREAD

**Issue by Qsnh** [codezero-be/encrypter#1]
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by ivanvermeyen** [comment]
Fixed in [#ddcfae5](https://github.com/codezero-be/encrypter/commit/ddcfae591848cadbfb5133b884220aed45477e80).

Also updated the dependencies. Since there was a PHP version conflict with some of the packages I bumped up the required PHP version to 5.6 or higher.

Make sure u pull in ~2.0 instead of ~1.0 for the updates.

Thanks for reporting :)

**Comment by Qsnh** [comment]
tks
